### ISSUE TITLE
Instrucciones

### ISSUE THREAD

**Issue by damianpintos** [matiasf/luisa_react_app#3]
Me parece que hay que agregar un link al lado del texto "Imágenes" que te lleve al bloque de instrucciones.
A su vez, en el bloque de instrucciones:
 - Sacar el texto: "Si hay más de una linea en el bloque, use "Shift" y "Enter" simultáneamente para separar las líneas.". No estamos tomando multilínea
 - Agregar algo así como: "cuando el texto esté en formato vertical, reportar imagen girada".

**Comment by matiasf** [comment]
Testeado en ambiente de prueba
